name: Publish image

on:
  push:
    branches:
      - "master"

jobs:
  publish-docker-image:
    if: github.repository_owner == 'obviyus'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/obviyus/bot:latest
          docker push ghcr.io/obviyus/bot:latest
